version: '3'

services:

  qualiexplore:
    ports:
      80:80
    
    image: hrabhijith/graphene-qualiexplore:latest
  
  gql-mongo:
    ports:
      - "5000:5000"

    env_file:
      - .env

    image: hrabhijith/gql-mongo:quali